version: "3.7"

services:
  frontend:
    build: ./frontend
    env_file:
      - frontend/.env
    ports:
      - 8000:80

  backend:
    build: ./backend
    env_file:
      - backend/.env
    links:
      - db
    ports:
      - 9000:9000

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: news
